# -*- coding:utf-8 -*-

TYPE_UNKNOWN = -1
TYPE_NUM_QUAN = 1
TYPE_PERCENT = 2
TYPE_RANGE_PERCENT = 3
TYPE_RANGE_QUAN = 4
TYPE_TIME = 5
TYPE_DATE = 6
TYPE_COLON_TIME = 7
TYPE_COLON_RATIO = 8
TYPE_DECIMAL = 9
TYPE_YEAR = 10
TYPE_DIGIT = 11
TYPE_RANGE = 12
TYPE_FRACTION = 13

SUB_TYPE_UNKNOWN = -1
SUB_TYPE_DIGIT = 0
SUB_TYPE_INTEGER = 1
SUB_TYPE_DIGIT_CHANGE = 2

MODE_RULE = 0
MODE_MODEL = 1
